In [3]:
import csv
import pandas as pd
from sklearn.linear_model import LogisticRegression 
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [4]:
import pandas as pd
import io

segment3_workflow2=pd.read_csv('segment3_workflowS2.csv')
segment3_workflow2.CASE_ID.mode()

0    1114684|484215|743082
dtype: object

In [5]:
import pandas as pd
import io

segment3_workflow3=pd.read_csv('segment3_workflowS3.csv')
segment3_workflow3.CASE_ID.mode()

0    1102908|470757|722758
dtype: object

In [167]:
import pandas as pd
import io

segment3_workflow4=pd.read_csv('segment3_workflowS4.csv')
segment3_workflow4.CASE_ID.mode()

0    1052275|402830|625246
dtype: object

In [6]:
segment3_workflow2.head()

,CASE_ID,WRKFLW_TSK_MAP_GROUPED,WRKFLW_TSK_MAP_DETAILED,PATH_CRDATETIME,ITEM_CRUSER,WRKFLW_ORG_TYPE_CRUSER,STATUS_ORDER,LATEST_STATUS,WRKFLW_PROCESS,QUERY_PART,...,ORIG_SPRD_CD,ORIG_SPRD_NM,SPK_CAT_TYPE_CD,BROAD_COURSE_LEVEL,DEGREETYPE,LIABILITY_CATEGORY_CD_RECODE,ORIG_LIABILITY_CATEGORY_CD_RECODE,OFFER_RELEASED_FG,OFFER_OUTCOME_CD,OFFER_CONDITIONS
0,1067449|424909|657898,Send for Assessment,Send for Assessment,7/12/2018 11:01:50,1067449,NaN,9,N,1. App to Assessment,Part 1 - Application ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
1,1067449|424909|657898,Acacdemic - Assessment Decision - Qualified,Acacdemic - Assessment Decision - Qualified,14/12/2018 15:55:39,RGORDON1,Academic,8,N,2. Perform Assessment,Part 4 - Assessment Decision,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
2,1067449|424909|657898,Assessment Outcome - Successful,Assessment Outcome - Successful,18/12/2018 11:34:06,KRIT,Faculty,7,N,2. Perform Assessment,Part 3 - Assessment Outcome,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
3,913640|554685|848410,Send for Assessment,Send for Assessment,3/12/2019 11:06:46,913640,NaN,1,Y,1. App to Assessment,Part 1 - Application ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,NaN,NaN,NaN
4,1021374|367597|573577,Send for Assessment,Send for Assessment,26/6/2018 11:26:41,1021374,NaN,17,N,1. App to Assessment,Part 1 - Application ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N

In [7]:
segment3_workflow3.head()

,CASE_ID,WRKFLW_TSK_MAP_GROUPED,WRKFLW_TSK_MAP_DETAILED,PATH_CRDATETIME,ITEM_CRUSER,WRKFLW_ORG_TYPE_CRUSER,STATUS_ORDER,LATEST_STATUS,WRKFLW_PROCESS,QUERY_PART,...,ORIG_SPRD_CD,ORIG_SPRD_NM,SPK_CAT_TYPE_CD,BROAD_COURSE_LEVEL,DEGREETYPE,LIABILITY_CATEGORY_CD_RECODE,ORIG_LIABILITY_CATEGORY_CD_RECODE,OFFER_RELEASED_FG,OFFER_OUTCOME_CD,OFFER_CONDITIONS
0,1067449|424909|657898,Assessment Outcome - Successful,Assessment Outcome - Successful,18/12/2018 11:34:06,KRIT,Faculty,7,N,2. Perform Assessment,Part 3 - Assessment Outcome,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
1,1067449|424909|657898,Create Offer,Create Offer,18/12/2018 11:34:51,KRIT,Faculty,6,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
2,1067449|424909|657898,Release Offer,Release Offer,18/12/2018 11:36:07,KRIT,Faculty,5,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
3,1021374|367597|573577,Assessment Outcome - Successful,Assessment Outcome - Successful,12/7/2018 10:07:14,ATKINSONM,Faculty,12,N,2. Perform Assessment,Part 3 - Assessment Outcome,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N
4,1021374|367597|573577,Create Offer,Create Offer,12/7/2018 10:07:30,ATKINSONM,Faculty,11,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N

In [168]:
segment3_workflow4.head()

,CASE_ID,WRKFLW_TSK_MAP_GROUPED,WRKFLW_TSK_MAP_DETAILED,PATH_CRDATETIME,ITEM_CRUSER,WRKFLW_ORG_TYPE_CRUSER,STATUS_ORDER,LATEST_STATUS,WRKFLW_PROCESS,QUERY_PART,REFERRAL_ID,APPLICATION_ID,APPLICATION_LINE_ID,STU_ID,STU_CITIZEN_CD,STU_CITIZEN_NM,STU_BIRTH_DT,STU_ABOR_TSI_CD,STU_ABOR_TSI_NM,STU_BIRTH_CNTRY_CD,STU_BIRTH_CNTRY_NM,STU_CTZN_CNTRY_CD,STU_CTZN_CNTRY_NM,SUBMISSION_METHOD,ENTRY_TYPE,ASSESSMENT_DECISION_SCORE,ASSESSMENT_DECISION_NM,ASSESSMENT_OUTCOME_NM,LAST_COUNTRY_EDUCATION,PREV_INST_NM_MAIN,PREV_INST_NM_ALT1,PREV_INST_NM_ALT2,PREFERENCE_NO,SPK_CD,SPK_FULL_TITLE,ORG_UNIT_CD,AVAIL_ORG_UNIT_NM,SUPPORTING_ORG,STUDY_MODE_CD,RETURNING_DEFERRAL,CURR_AVAIL_YR,CURR_STUDY_PERIOD,CURR_SPRD_CD,CURR_SPRD_NM,ORIG_AVAIL_YR,ORIG_STUDY_PERIOD,ORIG_SPRD_CD,ORIG_SPRD_NM,SPK_CAT_TYPE_CD,BROAD_COURSE_LEVEL,DEGREETYPE,LIABILITY_CATEGORY_CD_RECODE,ORIG_LIABILITY_CATEGORY_CD_RECODE,OFFER_RELEASED_FG,OFFER_OUTCOME_CD,OFFER_CONDITIONS
0,1067449|424909|657898,Release Offer,Release Offer,18/12/2018 11:36:07,KRIT,Faculty,5,N,3b. Offer stage,Part 2 - Application Line ID Workflow,NaN,424909,657898,1067449,1,Australian,22/7/1968 0:00:00,N,No,1100.0,Australia,1100.0,Australia,Online Application,Masters CW,0.0,Qualified,Successful,NaN,NaN,NaN,NaN,1,MC-ENGYSYS,Master of Energy Systems,400,Engineering,NaN,STD,N,2019,Start Year Intake,STYI,Start Year Intake,2019,Start Year Intake,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
1,1067449|424909|657898,OC - Satisfied - Other,OC - Satisfied - English language requirements,25/1/2019 15:18:53,KNAVIN,Academic Services,4,N,1. App to Assessment,Part 6 - Requirement Verify,Other,424909,657898,1067449,1,Australian,22/7/1968 0:00:00,N,No,1100.0,Australia,1100.0,Australia,Online Application,Masters CW,0.0,Qualified,Successful,NaN,NaN,NaN,NaN,1,MC-ENGYSYS,Master of Energy Systems,400,Engineering,NaN,STD,N,2019,Start Year Intake,STYI,Start Year Intake,2019,Start Year Intake,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
2,1067449|424909|657898,Accept,Accept,6/2/2019 9:12:01,KRIT,Faculty,3,N,4. Post offer,Part 2 - Application Line ID Workflow,NaN,424909,657898,1067449,1,Australian,22/7/1968 0:00:00,N,No,1100.0,Australia,1100.0,Australia,Online Application,Masters CW,0.0,Qualified,Successful,NaN,NaN,NaN,NaN,1,MC-ENGYSYS,Master of Energy Systems,400,Engineering,NaN,STD,N,2019,Start Year Intake,STYI,Start Year Intake,2019,Start Year Intake,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
3,1021374|367597|573577,Release Offer,Release Offer,12/7/2018 10:10:52,ATKINSONM,Faculty,10,N,3b. Offer stage,Part 2 - Application Line ID Workflow,NaN,367597,573577,1021374,2,New Zealander,17/9/1995 0:00:00,N,No,1201.0,New Zealand,1201.0,New Zealand,Online Application,Bachelor (equiv Aust 3yr deg),71.3,Qualified,Successful,New Zealand,"Auckland, University of",NaN,NaN,1,MC-ENG,Master of Engineering,400,Engineering,NaN,STD,N,2019,Start Year Intake,STYI,Start Year Intake,2019,Start Year Intake,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N
4,1021374|367597|573577,Accept,Accept,8/8/2018 12:14:54,ATKINSONM,Faculty,9,N,4. Post offer,Part 2 - Application Line ID Workflow,NaN,367597,573577,1021374,2,New Zealander,17/9/1995 0:00:00,N,No,1201.0,New Zealand,1201.0,New Zealand,Online Application,Bachelor (equiv Aust 3yr deg),71.3,Qualified,Successful,New Zealand,"Auckland, University of",NaN,NaN,1,MC-ENG,Master of Engineering,400,Engineering,NaN,STD,N,2019,Start Year Intake,STYI,Start Year Intake,2019,Start Year Intake,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N

In [8]:
segment3_workflow2=segment3_workflow2.drop(['WRKFLW_TSK_MAP_GROUPED', 'PATH_CRDATETIME','ITEM_CRUSER','WRKFLW_ORG_TYPE_CRUSER',
                         'STATUS_ORDER','LATEST_STATUS','WRKFLW_PROCESS','QUERY_PART','REFERRAL_ID',
                         'APPLICATION_ID','STU_ID','STU_CITIZEN_CD','STU_CITIZEN_NM','STU_BIRTH_DT',
                         'STU_ABOR_TSI_CD','STU_ABOR_TSI_NM','STU_BIRTH_CNTRY_CD','STU_BIRTH_CNTRY_NM',
                         'STU_CTZN_CNTRY_CD','STU_CTZN_CNTRY_NM','SUBMISSION_METHOD','ENTRY_TYPE',
                         'ASSESSMENT_DECISION_SCORE','ASSESSMENT_DECISION_NM','ASSESSMENT_OUTCOME_NM',
                         'LAST_COUNTRY_EDUCATION','PREV_INST_NM_MAIN','PREV_INST_NM_ALT1','PREV_INST_NM_ALT2',
                        'PREFERENCE_NO','SPK_CD','SPK_FULL_TITLE','ORG_UNIT_CD','AVAIL_ORG_UNIT_NM','SUPPORTING_ORG',
                        'STUDY_MODE_CD','RETURNING_DEFERRAL','CURR_AVAIL_YR','CURR_STUDY_PERIOD','CURR_SPRD_CD',
                        'CURR_SPRD_NM','ORIG_AVAIL_YR','ORIG_STUDY_PERIOD','ORIG_SPRD_CD','ORIG_SPRD_NM',
                         'SPK_CAT_TYPE_CD','BROAD_COURSE_LEVEL','DEGREETYPE','LIABILITY_CATEGORY_CD_RECODE',
                        'ORIG_LIABILITY_CATEGORY_CD_RECODE','OFFER_RELEASED_FG','OFFER_OUTCOME_CD','OFFER_CONDITIONS',
                        'APPLICATION_LINE_ID'], axis=1)
segment3_workflow2.head()

                 CASE_ID                      WRKFLW_TSK_MAP_DETAILED
0  1067449|424909|657898                          Send for Assessment
1  1067449|424909|657898  Acacdemic - Assessment Decision - Qualified
2  1067449|424909|657898              Assessment Outcome - Successful
3   913640|554685|848410                          Send for Assessment
4  1021374|367597|573577                          Send for Assessment

In [9]:
segment3_workflow3=segment3_workflow3.drop(['WRKFLW_TSK_MAP_GROUPED', 'PATH_CRDATETIME','ITEM_CRUSER','WRKFLW_ORG_TYPE_CRUSER',
                         'STATUS_ORDER','LATEST_STATUS','WRKFLW_PROCESS','QUERY_PART','REFERRAL_ID',
                         'APPLICATION_ID','STU_ID','STU_CITIZEN_CD','STU_CITIZEN_NM','STU_BIRTH_DT',
                         'STU_ABOR_TSI_CD','STU_ABOR_TSI_NM','STU_BIRTH_CNTRY_CD','STU_BIRTH_CNTRY_NM',
                         'STU_CTZN_CNTRY_CD','STU_CTZN_CNTRY_NM','SUBMISSION_METHOD','ENTRY_TYPE',
                         'ASSESSMENT_DECISION_SCORE','ASSESSMENT_DECISION_NM','ASSESSMENT_OUTCOME_NM',
                         'LAST_COUNTRY_EDUCATION','PREV_INST_NM_MAIN','PREV_INST_NM_ALT1','PREV_INST_NM_ALT2',
                        'PREFERENCE_NO','SPK_CD','SPK_FULL_TITLE','ORG_UNIT_CD','AVAIL_ORG_UNIT_NM','SUPPORTING_ORG',
                        'STUDY_MODE_CD','RETURNING_DEFERRAL','CURR_AVAIL_YR','CURR_STUDY_PERIOD','CURR_SPRD_CD',
                        'CURR_SPRD_NM','ORIG_AVAIL_YR','ORIG_STUDY_PERIOD','ORIG_SPRD_CD','ORIG_SPRD_NM',
                         'SPK_CAT_TYPE_CD','BROAD_COURSE_LEVEL','DEGREETYPE','LIABILITY_CATEGORY_CD_RECODE',
                        'ORIG_LIABILITY_CATEGORY_CD_RECODE','OFFER_RELEASED_FG','OFFER_OUTCOME_CD','OFFER_CONDITIONS',
                        'APPLICATION_LINE_ID'], axis=1)
segment3_workflow3.head()

                 CASE_ID          WRKFLW_TSK_MAP_DETAILED
0  1067449|424909|657898  Assessment Outcome - Successful
1  1067449|424909|657898                     Create Offer
2  1067449|424909|657898                    Release Offer
3  1021374|367597|573577  Assessment Outcome - Successful
4  1021374|367597|573577                     Create Offer

In [169]:
segment3_workflow4=segment3_workflow4.drop(['WRKFLW_TSK_MAP_GROUPED', 'PATH_CRDATETIME','ITEM_CRUSER','WRKFLW_ORG_TYPE_CRUSER',
                         'STATUS_ORDER','LATEST_STATUS','WRKFLW_PROCESS','QUERY_PART','REFERRAL_ID',
                         'APPLICATION_ID','STU_ID','STU_CITIZEN_CD','STU_CITIZEN_NM','STU_BIRTH_DT',
                         'STU_ABOR_TSI_CD','STU_ABOR_TSI_NM','STU_BIRTH_CNTRY_CD','STU_BIRTH_CNTRY_NM',
                         'STU_CTZN_CNTRY_CD','STU_CTZN_CNTRY_NM','SUBMISSION_METHOD','ENTRY_TYPE',
                         'ASSESSMENT_DECISION_SCORE','ASSESSMENT_DECISION_NM','ASSESSMENT_OUTCOME_NM',
                         'LAST_COUNTRY_EDUCATION','PREV_INST_NM_MAIN','PREV_INST_NM_ALT1','PREV_INST_NM_ALT2',
                        'PREFERENCE_NO','SPK_CD','SPK_FULL_TITLE','ORG_UNIT_CD','AVAIL_ORG_UNIT_NM','SUPPORTING_ORG',
                        'STUDY_MODE_CD','RETURNING_DEFERRAL','CURR_AVAIL_YR','CURR_STUDY_PERIOD','CURR_SPRD_CD',
                        'CURR_SPRD_NM','ORIG_AVAIL_YR','ORIG_STUDY_PERIOD','ORIG_SPRD_CD','ORIG_SPRD_NM',
                         'SPK_CAT_TYPE_CD','BROAD_COURSE_LEVEL','DEGREETYPE','LIABILITY_CATEGORY_CD_RECODE',
                        'ORIG_LIABILITY_CATEGORY_CD_RECODE','OFFER_RELEASED_FG','OFFER_OUTCOME_CD','OFFER_CONDITIONS',
                        'APPLICATION_LINE_ID'], axis=1)
segment3_workflow4.head()

                 CASE_ID                         WRKFLW_TSK_MAP_DETAILED
0  1067449|424909|657898                                   Release Offer
1  1067449|424909|657898  OC - Satisfied - English language requirements
2  1067449|424909|657898                                          Accept
3  1021374|367597|573577                                   Release Offer
4  1021374|367597|573577                                          Accept

In [170]:
numOfWorkflowProcesses=segment3_workflow2.groupby('CASE_ID').CASE_ID.count()
numOfWorkflowProcesses.head()

CASE_ID
1000727|431447|668147    11
1001829|336678|526826     3
1001829|336678|526827     3
1001877|336757|526956    11
1002271|337186|527523     8
Name: CASE_ID, dtype: int64

In [171]:
numOfWorkflowProcesses2=segment3_workflow3.groupby('CASE_ID').CASE_ID.count()
numOfWorkflowProcesses2.head()

CASE_ID
1000727|431447|668147    4
1001829|336678|526826    3
1001877|336757|526956    3
1002271|337186|527523    3
1007394|346044|540306    3
Name: CASE_ID, dtype: int64

In [172]:
numOfWorkflowProcesses3=segment3_workflow4.groupby('CASE_ID').CASE_ID.count()
numOfWorkflowProcesses3.head()

CASE_ID
1000727|431447|668147    2
1001829|336678|526826    2
1001877|336757|526956    1
1002271|337186|527523    2
1007394|346044|540306    2
Name: CASE_ID, dtype: int64

In [173]:
counts = segment3_workflow2['CASE_ID'].value_counts()

In [174]:
counts2 = segment3_workflow3['CASE_ID'].value_counts()

In [175]:
counts3 = segment3_workflow4['CASE_ID'].value_counts()

In [176]:
counts.head()

1114684|484215|743082    22
1028582|370276|577743    16
1076583|437721|676610    15
1019820|360156|561476    15
1025815|366554|572153    15
Name: CASE_ID, dtype: int64

In [177]:
counts2.head()

1102908|470757|722758    12
1147799|528824|809849    11
1025815|366554|572153    10
1120436|490900|754192     9
1140264|517887|794176     9
Name: CASE_ID, dtype: int64

In [178]:
counts3.head()

1052275|402830|625246    7
954468|360490|561961     6
1152919|538301|823869    6
1025305|366531|571922    6
1076747|476620|731205    5
Name: CASE_ID, dtype: int64

In [297]:
filtered = counts[counts > 10]
seg3_count1=segment3_workflow2[segment3_workflow2['CASE_ID'].isin(filtered.index)]

In [298]:
filtered2 = counts2[counts2 > 10]
seg3_count2=segment3_workflow3[segment3_workflow3['CASE_ID'].isin(filtered.index)]

In [299]:
filtered3 = counts3[counts3 > 10]
seg3_count3=segment3_workflow4[segment3_workflow4['CASE_ID'].isin(filtered.index)]

In [300]:
seg3_count1['CASE_ID'].nunique()

16

In [301]:
seg3_count1.head()

                  CASE_ID                            WRKFLW_TSK_MAP_DETAILED
12  1124743|501279|769447                                Send for Assessment
13  1124743|501279|769447                                     Back to Triage
14  1124743|501279|769447                                Send for Assessment
15  1124743|501279|769447  AR - Created - Assessment information (Coursew...
16  1124743|501279|769447  AR - Satisfied - Assessment information (Cours...

In [302]:
seg3_count2['CASE_ID'].nunique()

14

In [303]:
seg3_count2.head()

                  CASE_ID          WRKFLW_TSK_MAP_DETAILED
7   1124743|501279|769447  Assessment Outcome - Successful
8   1124743|501279|769447                     Create Offer
9   1124743|501279|769447                    Release Offer
34  1022190|362029|564420  Assessment Outcome - Successful
35  1022190|362029|564420                     Create Offer

In [304]:
seg3_count3['CASE_ID'].nunique()

12

In [305]:
seg3_count3.head()

                  CASE_ID WRKFLW_TSK_MAP_DETAILED
5   1124743|501279|769447           Release Offer
6   1124743|501279|769447                 Decline
18  1022190|362029|564420           Release Offer
19  1022190|362029|564420                  Accept
48  1000727|431447|668147           Release Offer

In [306]:
frames = [seg3_count1, seg3_count2, seg3_count3]
count_12=pd.concat(frames)

In [307]:
y = pd.get_dummies(seg3_count1.WRKFLW_TSK_MAP_DETAILED)
y=y[:0]

In [308]:
y

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1), AR - Created - Further information (1), AR - Created - Further information (2), AR - Created - Payment of international application fee, AR - Not Satisfied - English language proficiency, AR - Requested - Academic results for prior tertiary studies, AR - Requested - Further information (1), AR - Requested - Official syllabus or subject descriptions (in English), AR - Requested - Payment of international application fee, AR - Satisfied - Academic results for prior tertiary studies, AR - Satisfied - Assessment information (Coursework) (1), AR - Satisfied - Credit for previous study, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - Curriculum Vitae, AR - Satisfied - English language proficiency, AR - Satisfied - Entry points (Master of Information Technology), AR - Satisfied - Further information (1), AR - Satisfied - Further information (2), AR - Satisfied - Graduate Access Melbourne, AR - Satisfied - Specialisation (Master of Information Technology), AR - Satisfied - Transcript Ã» My eQuals, Acacdemic - Assessment Decision - No Decision, Acacdemic - Assessment Decision - Not Qualified, Acacdemic - Assessment Decision - Qualified, Assessment Decision - No Decision, Assessment Decision - Not Qualified, Assessment Decision - Qualified, Assessment Outcome - Higher Preference Successful, Assessment Outcome - Not Successful, Assessment Outcome - Successful, Back to Triage, End My Assessment, OC - Created - English language requirements, OC - Created - Evidence of course completion, OC - Reviewed - English language requirements, Put Assessment On-Hold, Put Triage On-Hold, Release Assessment Hold, Release Triage Hold, Send for Assessment]
Index: []

In [309]:
y2 = pd.get_dummies(seg3_count2.WRKFLW_TSK_MAP_DETAILED)
y2=y2[:0]

In [310]:
y2

Empty DataFrame
Columns: [AR - Satisfied - Graduate Access Melbourne, Assessment Decision - Qualified, Assessment Outcome - Not Successful, Assessment Outcome - Successful, Create Offer, OC - Created - Evidence of course completion, Put Assessment On-Hold, Release Assessment Hold, Release Offer]
Index: []

In [311]:
y3=pd.merge(y, y2, on='Assessment Outcome - Successful')
y3

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1), AR - Created - Further information (1), AR - Created - Further information (2), AR - Created - Payment of international application fee, AR - Not Satisfied - English language proficiency, AR - Requested - Academic results for prior tertiary studies, AR - Requested - Further information (1), AR - Requested - Official syllabus or subject descriptions (in English), AR - Requested - Payment of international application fee, AR - Satisfied - Academic results for prior tertiary studies, AR - Satisfied - Assessment information (Coursework) (1), AR - Satisfied - Credit for previous study, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - Curriculum Vitae, AR - Satisfied - English language proficiency, AR - Satisfied - Entry points (Master of Information Technology), AR - Satisfied - Further information (1), AR - Satisfied - Further information (2), AR - Satisfied - Graduate Access Melbourne_x, AR - Satisfied - Specialisation (Master of Information Technology), AR - Satisfied - Transcript Ã» My eQuals, Acacdemic - Assessment Decision - No Decision, Acacdemic - Assessment Decision - Not Qualified, Acacdemic - Assessment Decision - Qualified, Assessment Decision - No Decision, Assessment Decision - Not Qualified, Assessment Decision - Qualified_x, Assessment Outcome - Higher Preference Successful, Assessment Outcome - Not Successful_x, Back to Triage, End My Assessment, OC - Created - English language requirements, OC - Created - Evidence of course completion_x, OC - Reviewed - English language requirements, Put Assessment On-Hold_x, Put Triage On-Hold, Release Assessment Hold_x, Release Triage Hold, Send for Assessment, AR - Satisfied - Graduate Access Melbourne_y, Assessment Decision - Qualified_y, Assessment Outcome - Not Successful_y, Assessment Outcome - Successful, Create Offer, OC - Created - Evidence of course completion_y, Put Assessment On-Hold_y, Release Assessment Hold_y, Release Offer]
Index: []

In [312]:
y3.columns = y3.columns.str.replace("_x", "")

In [313]:
y3.columns = y3.columns.str.replace("_y", "")

In [314]:
y3 = y3.loc[:,~y3.columns.duplicated()]

In [315]:
y3.shape

(0, 42)

In [316]:
y3

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1), AR - Created - Further information (1), AR - Created - Further information (2), AR - Created - Payment of international application fee, AR - Not Satisfied - English language proficiency, AR - Requested - Academic results for prior tertiary studies, AR - Requested - Further information (1), AR - Requested - Official syllabus or subject descriptions (in English), AR - Requested - Payment of international application fee, AR - Satisfied - Academic results for prior tertiary studies, AR - Satisfied - Assessment information (Coursework) (1), AR - Satisfied - Credit for previous study, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - Curriculum Vitae, AR - Satisfied - English language proficiency, AR - Satisfied - Entry points (Master of Information Technology), AR - Satisfied - Further information (1), AR - Satisfied - Further information (2), AR - Satisfied - Graduate Access Melbourne, AR - Satisfied - Specialisation (Master of Information Technology), AR - Satisfied - Transcript Ã» My eQuals, Acacdemic - Assessment Decision - No Decision, Acacdemic - Assessment Decision - Not Qualified, Acacdemic - Assessment Decision - Qualified, Assessment Decision - No Decision, Assessment Decision - Not Qualified, Assessment Decision - Qualified, Assessment Outcome - Higher Preference Successful, Assessment Outcome - Not Successful, Back to Triage, End My Assessment, OC - Created - English language requirements, OC - Created - Evidence of course completion, OC - Reviewed - English language requirements, Put Assessment On-Hold, Put Triage On-Hold, Release Assessment Hold, Release Triage Hold, Send for Assessment, Assessment Outcome - Successful, Create Offer, Release Offer]
Index: []

In [317]:
y4 = pd.get_dummies(seg3_count3.WRKFLW_TSK_MAP_DETAILED)
y4=y4[:0]

In [318]:
y5=pd.merge(y3, y4, on='Release Offer')
y5

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1), AR - Created - Further information (1), AR - Created - Further information (2), AR - Created - Payment of international application fee, AR - Not Satisfied - English language proficiency, AR - Requested - Academic results for prior tertiary studies, AR - Requested - Further information (1), AR - Requested - Official syllabus or subject descriptions (in English), AR - Requested - Payment of international application fee, AR - Satisfied - Academic results for prior tertiary studies, AR - Satisfied - Assessment information (Coursework) (1), AR - Satisfied - Credit for previous study, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - Curriculum Vitae, AR - Satisfied - English language proficiency, AR - Satisfied - Entry points (Master of Information Technology), AR - Satisfied - Further information (1), AR - Satisfied - Further information (2), AR - Satisfied - Graduate Access Melbourne_x, AR - Satisfied - Specialisation (Master of Information Technology), AR - Satisfied - Transcript Ã» My eQuals, Acacdemic - Assessment Decision - No Decision, Acacdemic - Assessment Decision - Not Qualified, Acacdemic - Assessment Decision - Qualified, Assessment Decision - No Decision, Assessment Decision - Not Qualified, Assessment Decision - Qualified, Assessment Outcome - Higher Preference Successful, Assessment Outcome - Not Successful, Back to Triage, End My Assessment, OC - Created - English language requirements, OC - Created - Evidence of course completion, OC - Reviewed - English language requirements_x, Put Assessment On-Hold, Put Triage On-Hold, Release Assessment Hold, Release Triage Hold, Send for Assessment, Assessment Outcome - Successful, Create Offer, AR - Satisfied - Graduate Access Melbourne_y, Accept, Decline, Defer, OC - Reviewed - English language requirements_y, Release Offer]
Index: []

In [319]:
y5.columns = y5.columns.str.replace("_x", "")

In [320]:
y5.columns = y5.columns.str.replace("_y", "")

In [321]:
y5 = y5.loc[:,~y5.columns.duplicated()]

In [322]:
y5.shape

(0, 45)

In [323]:
y5

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1), AR - Created - Further information (1), AR - Created - Further information (2), AR - Created - Payment of international application fee, AR - Not Satisfied - English language proficiency, AR - Requested - Academic results for prior tertiary studies, AR - Requested - Further information (1), AR - Requested - Official syllabus or subject descriptions (in English), AR - Requested - Payment of international application fee, AR - Satisfied - Academic results for prior tertiary studies, AR - Satisfied - Assessment information (Coursework) (1), AR - Satisfied - Credit for previous study, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - Curriculum Vitae, AR - Satisfied - English language proficiency, AR - Satisfied - Entry points (Master of Information Technology), AR - Satisfied - Further information (1), AR - Satisfied - Further information (2), AR - Satisfied - Graduate Access Melbourne, AR - Satisfied - Specialisation (Master of Information Technology), AR - Satisfied - Transcript Ã» My eQuals, Acacdemic - Assessment Decision - No Decision, Acacdemic - Assessment Decision - Not Qualified, Acacdemic - Assessment Decision - Qualified, Assessment Decision - No Decision, Assessment Decision - Not Qualified, Assessment Decision - Qualified, Assessment Outcome - Higher Preference Successful, Assessment Outcome - Not Successful, Back to Triage, End My Assessment, OC - Created - English language requirements, OC - Created - Evidence of course completion, OC - Reviewed - English language requirements, Put Assessment On-Hold, Put Triage On-Hold, Release Assessment Hold, Release Triage Hold, Send for Assessment, Assessment Outcome - Successful, Create Offer, Accept, Decline, Defer, Release Offer]
Index: []

In [324]:
y5["CASE_ID"]=""

In [325]:
col_name="CASE_ID"
first_col = y5.pop(col_name)

In [326]:
y5.insert(0, col_name, first_col)

In [327]:
y5['CASE_ID']=count_12['CASE_ID'].unique()

<ipython-input-327-da8cd2d0614a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y5['CASE_ID']=count_12['CASE_ID'].unique()

In [328]:
import numpy as np
y5 = y5.replace(np.nan,0, regex=True)
y5.head()

,CASE_ID,AR - Created - Assessment information (Coursework) (1),AR - Created - Further information (1),AR - Created - Further information (2),AR - Created - Payment of international application fee,AR - Not Satisfied - English language proficiency,AR - Requested - Academic results for prior tertiary studies,AR - Requested - Further information (1),AR - Requested - Official syllabus or subject descriptions (in English),AR - Requested - Payment of international application fee,AR - Satisfied - Academic results for prior tertiary studies,AR - Satisfied - Assessment information (Coursework) (1),AR - Satisfied - Credit for previous study,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - Curriculum Vitae,AR - Satisfied - English language proficiency,AR - Satisfied - Entry points (Master of Information Technology),AR - Satisfied - Further information (1),AR - Satisfied - Further information (2),AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Specialisation (Master of Information Technology),AR - Satisfied - Transcript Ã» My eQuals,Acacdemic - Assessment Decision - No Decision,Acacdemic - Assessment Decision - Not Qualified,Acacdemic - Assessment Decision - Qualified,Assessment Decision - No Decision,Assessment Decision - Not Qualified,Assessment Decision - Qualified,Assessment Outcome - Higher Preference Successful,Assessment Outcome - Not Successful,Back to Triage,End My Assessment,OC - Created - English language requirements,OC - Created - Evidence of course completion,OC - Reviewed - English language requirements,Put Assessment On-Hold,Put Triage On-Hold,Release Assessment Hold,Release Triage Hold,Send for Assessment,Assessment Outcome - Successful,Create Offer,Accept,Decline,Defer,Release Offer
0,1124743|501279|769447,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1022190|362029|564420,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1000727|431447|668147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1076583|437721|676610,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1114684|484215|743082,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [329]:
dict_1=count_12.to_dict(orient='list')

In [330]:
case_id = dict_1['CASE_ID']

In [331]:
workflow = dict_1['WRKFLW_TSK_MAP_DETAILED']

In [332]:
print(type(workflow))
print(len(workflow))

<class 'list'>
282

In [333]:
from collections import defaultdict

case_wf_dict = defaultdict(list)

for i in range(len(case_id)):
    item = case_id[i]
    case_wf_dict[item].append(workflow[i])
print(len(case_wf_dict))

16

In [334]:
y5 = y5.set_index('CASE_ID')

In [335]:
y5.head()

,AR - Created - Assessment information (Coursework) (1),AR - Created - Further information (1),AR - Created - Further information (2),AR - Created - Payment of international application fee,AR - Not Satisfied - English language proficiency,AR - Requested - Academic results for prior tertiary studies,AR - Requested - Further information (1),AR - Requested - Official syllabus or subject descriptions (in English),AR - Requested - Payment of international application fee,AR - Satisfied - Academic results for prior tertiary studies,AR - Satisfied - Assessment information (Coursework) (1),AR - Satisfied - Credit for previous study,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - Curriculum Vitae,AR - Satisfied - English language proficiency,AR - Satisfied - Entry points (Master of Information Technology),AR - Satisfied - Further information (1),AR - Satisfied - Further information (2),AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Specialisation (Master of Information Technology),AR - Satisfied - Transcript Ã» My eQuals,Acacdemic - Assessment Decision - No Decision,Acacdemic - Assessment Decision - Not Qualified,Acacdemic - Assessment Decision - Qualified,Assessment Decision - No Decision,Assessment Decision - Not Qualified,Assessment Decision - Qualified,Assessment Outcome - Higher Preference Successful,Assessment Outcome - Not Successful,Back to Triage,End My Assessment,OC - Created - English language requirements,OC - Created - Evidence of course completion,OC - Reviewed - English language requirements,Put Assessment On-Hold,Put Triage On-Hold,Release Assessment Hold,Release Triage Hold,Send for Assessment,Assessment Outcome - Successful,Create Offer,Accept,Decline,Defer,Release Offer
CASE_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1124743|501279|769447,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1022190|362029|564420,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1000727|431447|668147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1076583|437721|676610,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1114684|484215|743082,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [336]:
y_col_name = y5.columns.values.tolist()
print(y_col_name)

['AR - Created - Assessment information (Coursework) (1)', 'AR - Created - Further information (1)', 'AR - Created - Further information (2)', 'AR - Created - Payment of international application fee', 'AR - Not Satisfied - English language proficiency', 'AR - Requested - Academic results for prior tertiary studies', 'AR - Requested - Further information (1)', 'AR - Requested - Official syllabus or subject descriptions (in English)', 'AR - Requested - Payment of international application fee', 'AR - Satisfied - Academic results for prior tertiary studies', 'AR - Satisfied - Assessment information (Coursework) (1)', 'AR - Satisfied - Credit for previous study', 'AR - Satisfied - Current enrolment at the University of Melbourne', 'AR - Satisfied - Curriculum Vitae', 'AR - Satisfied - English language proficiency', 'AR - Satisfied - Entry points (Master of Information Technology)', 'AR - Satisfied - Further information (1)', 'AR - Satisfied - Further information (2)', 'AR - Satisfied - Graduate Access Melbourne', 'AR - Satisfied - Specialisation (Master of Information Technology)', 'AR - Satisfied - Transcript Ã» My eQuals', 'Acacdemic - Assessment Decision - No Decision', 'Acacdemic - Assessment Decision - Not Qualified', 'Acacdemic - Assessment Decision - Qualified', 'Assessment Decision - No Decision', 'Assessment Decision - Not Qualified', 'Assessment Decision - Qualified', 'Assessment Outcome - Higher Preference Successful', 'Assessment Outcome - Not Successful', 'Back to Triage', 'End My Assessment', 'OC - Created - English language requirements', 'OC - Created - Evidence of course completion', 'OC - Reviewed - English language requirements', 'Put Assessment On-Hold', 'Put Triage On-Hold', 'Release Assessment Hold', 'Release Triage Hold', 'Send for Assessment', 'Assessment Outcome - Successful', 'Create Offer', 'Accept', 'Decline', 'Defer', 'Release Offer']

In [337]:
for key in case_wf_dict.keys():
    for process in case_wf_dict[key]:
        if process in y_col_name:
            y5.loc[key, process] = 1
        else:
            continue

In [338]:
pd.set_option('display.max_columns', 100)

In [339]:
y5['Send for Assessment'].head()

CASE_ID
1124743|501279|769447    1.0
1022190|362029|564420    1.0
1000727|431447|668147    1.0
1076583|437721|676610    1.0
1114684|484215|743082    1.0
Name: Send for Assessment, dtype: float64

In [340]:
def movecol(df, cols_to_move=[], ref_col='', place='After'):
    
    cols = df.columns.tolist()
    if place == 'After':
        seg1 = cols[:list(cols).index(ref_col) + 1]
        seg2 = cols_to_move
    if place == 'Before':
        seg1 = cols[:list(cols).index(ref_col)]
        seg2 = cols_to_move + [ref_col]
    
    seg1 = [i for i in seg1 if i not in seg2]
    seg3 = [i for i in cols if i not in seg1 + seg2]
    
    return(df[seg1 + seg2 + seg3])

In [341]:
y5.head()

,AR - Created - Assessment information (Coursework) (1),AR - Created - Further information (1),AR - Created - Further information (2),AR - Created - Payment of international application fee,AR - Not Satisfied - English language proficiency,AR - Requested - Academic results for prior tertiary studies,AR - Requested - Further information (1),AR - Requested - Official syllabus or subject descriptions (in English),AR - Requested - Payment of international application fee,AR - Satisfied - Academic results for prior tertiary studies,AR - Satisfied - Assessment information (Coursework) (1),AR - Satisfied - Credit for previous study,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - Curriculum Vitae,AR - Satisfied - English language proficiency,AR - Satisfied - Entry points (Master of Information Technology),AR - Satisfied - Further information (1),AR - Satisfied - Further information (2),AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Specialisation (Master of Information Technology),AR - Satisfied - Transcript Ã» My eQuals,Acacdemic - Assessment Decision - No Decision,Acacdemic - Assessment Decision - Not Qualified,Acacdemic - Assessment Decision - Qualified,Assessment Decision - No Decision,Assessment Decision - Not Qualified,Assessment Decision - Qualified,Assessment Outcome - Higher Preference Successful,Assessment Outcome - Not Successful,Back to Triage,End My Assessment,OC - Created - English language requirements,OC - Created - Evidence of course completion,OC - Reviewed - English language requirements,Put Assessment On-Hold,Put Triage On-Hold,Release Assessment Hold,Release Triage Hold,Send for Assessment,Assessment Outcome - Successful,Create Offer,Accept,Decline,Defer,Release Offer
CASE_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1124743|501279|769447,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
1022190|362029|564420,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
1000727|431447|668147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
1076583|437721|676610,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1114684|484215|743082,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0

In [342]:
y5 = movecol(y5, 
             cols_to_move=['Accept'], 
             ref_col='Release Offer',
             place='After')

In [343]:
y5 = movecol(y5, 
             cols_to_move=['Defer'], 
             ref_col='Release Offer',
             place='After')

In [344]:
y5.shape

(16, 45)

In [345]:
y5=y5.fillna(0.0)

In [350]:
X=y5.iloc[:,0:43].values
Y=y5.iloc[:,43].values

In [351]:
#spliting dataset
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size = 0.3,random_state=0)

In [352]:
# K Nearest Neighbors
Knn = KNeighborsClassifier(n_neighbors=5)
Knn.fit(x_train,y_train)

KNeighborsClassifier()

In [353]:
knn_predict=Knn.predict(x_test)
print("accuracy: {}%".format(round(accuracy_score(y_test, knn_predict)*100,2)))

accuracy: 100.0%