In [1]:
import csv
import pandas as pd
from sklearn.linear_model import LogisticRegression 
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [3]:
segment2_workflow4=pd.read_csv('segment2_workflowS4.csv')
segment2_workflow4.CASE_ID.mode()

0    1159451|547002|837360
dtype: object

In [4]:
segment2_workflow4.head()

,CASE_ID,WRKFLW_TSK_MAP_GROUPED,WRKFLW_TSK_MAP_DETAILED,PATH_CRDATETIME,ITEM_CRUSER,WRKFLW_ORG_TYPE_CRUSER,STATUS_ORDER,LATEST_STATUS,WRKFLW_PROCESS,QUERY_PART,...,ORIG_SPRD_CD,ORIG_SPRD_NM,SPK_CAT_TYPE_CD,BROAD_COURSE_LEVEL,DEGREETYPE,LIABILITY_CATEGORY_CD_RECODE,ORIG_LIABILITY_CATEGORY_CD_RECODE,OFFER_RELEASED_FG,OFFER_OUTCOME_CD,OFFER_CONDITIONS
0,1139423|516709|792465,Release Offer,Release Offer,27/11/2019 10:36:49,CHRISTINAA,Faculty,7,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AS,AS,Y,$ACC,Y
1,1139423|516709|792465,AR - Satisfied - further information,AR - Satisfied - Further information (1),3/12/2019 12:22:48,MTSC,Academic Services,6,N,1. App to Assessment,Part 6 - Requirement Verify,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AS,AS,Y,$ACC,Y
2,1139423|516709|792465,Accept,Accept,4/12/2019 19:48:21,CHRISTINAA,Faculty,5,N,4. Post offer,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AS,AS,Y,$ACC,Y
3,836673|527943|808557,Release Offer,Release Offer,30/10/2019 16:10:10,ATKINSONM,Faculty,3,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AS,AS,Y,$DEF,Y
4,836673|527943|808557,OC - Satisfied - Other,OC - Satisfied - Evidence of course completion,9/12/2019 18:43:48,SAHM,Academic Services,2,N,1. App to Assessment,Part 6 - Requirement Verify,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AS,AS,Y,$DEF,Y

In [5]:
segment2_workflow4['WRKFLW_TSK_MAP_DETAILED'].nunique()

45

In [6]:
segment2_workflow4=segment2_workflow4.drop(['WRKFLW_TSK_MAP_GROUPED', 'PATH_CRDATETIME','ITEM_CRUSER','WRKFLW_ORG_TYPE_CRUSER',
                         'STATUS_ORDER','LATEST_STATUS','WRKFLW_PROCESS','QUERY_PART','REFERRAL_ID',
                         'APPLICATION_ID','STU_ID','STU_CITIZEN_CD','STU_CITIZEN_NM','STU_BIRTH_DT',
                         'STU_ABOR_TSI_CD','STU_ABOR_TSI_NM','STU_BIRTH_CNTRY_CD','STU_BIRTH_CNTRY_NM',
                         'STU_CTZN_CNTRY_CD','STU_CTZN_CNTRY_NM','SUBMISSION_METHOD','ENTRY_TYPE',
                         'ASSESSMENT_DECISION_SCORE','ASSESSMENT_DECISION_NM','ASSESSMENT_OUTCOME_NM',
                         'LAST_COUNTRY_EDUCATION','PREV_INST_NM_MAIN','PREV_INST_NM_ALT1','PREV_INST_NM_ALT2',
                        'PREFERENCE_NO','SPK_CD','SPK_FULL_TITLE','ORG_UNIT_CD','AVAIL_ORG_UNIT_NM','SUPPORTING_ORG',
                        'STUDY_MODE_CD','RETURNING_DEFERRAL','CURR_AVAIL_YR','CURR_STUDY_PERIOD','CURR_SPRD_CD',
                        'CURR_SPRD_NM','ORIG_AVAIL_YR','ORIG_STUDY_PERIOD','ORIG_SPRD_CD','ORIG_SPRD_NM',
                         'SPK_CAT_TYPE_CD','BROAD_COURSE_LEVEL','DEGREETYPE','LIABILITY_CATEGORY_CD_RECODE',
                        'ORIG_LIABILITY_CATEGORY_CD_RECODE','OFFER_RELEASED_FG','OFFER_OUTCOME_CD','OFFER_CONDITIONS',
                        'APPLICATION_LINE_ID'], axis=1)
segment2_workflow4.head()

                 CASE_ID                         WRKFLW_TSK_MAP_DETAILED
0  1139423|516709|792465                                   Release Offer
1  1139423|516709|792465        AR - Satisfied - Further information (1)
2  1139423|516709|792465                                          Accept
3   836673|527943|808557                                   Release Offer
4   836673|527943|808557  OC - Satisfied - Evidence of course completion

In [7]:
numOfWorkflowProcesses=segment2_workflow4.groupby('CASE_ID').CASE_ID.count()
numOfWorkflowProcesses.head()

CASE_ID
1000870|335395|524947    2
1001146|382147|595222    3
1003741|551868|844300    2
1006581|343740|536885    2
1006755|342978|535822    2
Name: CASE_ID, dtype: int64

In [8]:
counts = segment2_workflow4['CASE_ID'].value_counts()

In [9]:
counts.head()

1159451|547002|837360    11
830859|368383|574848      8
910085|483734|742248      7
834481|553314|846375      7
766492|543478|831915      6
Name: CASE_ID, dtype: int64

In [195]:
filtered = counts[counts == 7]
seg1_count1=segment2_workflow4[segment2_workflow4['CASE_ID'].isin(filtered.index)]

In [196]:
seg1_count1['CASE_ID'].nunique()

2

In [197]:
seg1_count1.head()

                   CASE_ID                         WRKFLW_TSK_MAP_DETAILED
1014  910085|483734|742248                                   Release Offer
1015  910085|483734|742248                          Put Assessment On-Hold
1016  910085|483734|742248    OC - Created - Evidence of course completion
1017  910085|483734|742248                         Release Assessment Hold
1018  910085|483734|742248  OC - Satisfied - Evidence of course completion

In [159]:
y = pd.get_dummies(seg1_count1.WRKFLW_TSK_MAP_DETAILED)
y=y[:0]

In [160]:
y

Empty DataFrame
Columns: [AR - Satisfied - Advanced Standing, AR - Satisfied - Credit for previous study, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - English language proficiency, AR - Satisfied - Further information (1), AR - Satisfied - Further information Ã» Preference order required as submitted multiple 1st prefer applications, AR - Satisfied - Graduate Access Melbourne, AR - Satisfied - Official syllabus or subject descriptions (in English), Accept, Assessment Decision - No Decision, Assessment Decision - Qualified, OC - Created - English language requirements, OC - Reviewed - English language requirements, OC - Satisfied - English language requirements, OC - Satisfied - Evidence of course completion, Put Assessment On-Hold, Release Offer]
Index: []

In [161]:
y["CASE_ID"]=""

In [162]:
col_name="CASE_ID"
first_col = y.pop(col_name)

In [163]:
y.insert(0, col_name, first_col)

In [164]:
y['CASE_ID']=seg1_count1['CASE_ID'].unique()

In [165]:
import numpy as np
y = y.replace(np.nan,0, regex=True)
y.head()

,CASE_ID,AR - Satisfied - Advanced Standing,AR - Satisfied - Credit for previous study,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - English language proficiency,AR - Satisfied - Further information (1),AR - Satisfied - Further information Ã» Preference order required as submitted multiple 1st prefer applications,AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Official syllabus or subject descriptions (in English),Accept,Assessment Decision - No Decision,Assessment Decision - Qualified,OC - Created - English language requirements,OC - Reviewed - English language requirements,OC - Satisfied - English language requirements,OC - Satisfied - Evidence of course completion,Put Assessment On-Hold,Release Offer
0,766492|543478|831915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,582122|518867|795643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,832148|505702|776061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,831220|378450|589682,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1159316|546833|837110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [166]:
dict_1=seg1_count1.to_dict(orient='list')

In [167]:
case_id = dict_1['CASE_ID']

In [168]:
workflow = dict_1['WRKFLW_TSK_MAP_DETAILED']

In [169]:
print(type(workflow))
print(len(workflow))

<class 'list'>
36

In [170]:
from collections import defaultdict

case_wf_dict = defaultdict(list)

for i in range(len(case_id)):
    item = case_id[i]
    case_wf_dict[item].append(workflow[i])
print(len(case_wf_dict))

6

In [171]:
y = y.set_index('CASE_ID')

In [172]:
y.head()

,AR - Satisfied - Advanced Standing,AR - Satisfied - Credit for previous study,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - English language proficiency,AR - Satisfied - Further information (1),AR - Satisfied - Further information Ã» Preference order required as submitted multiple 1st prefer applications,AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Official syllabus or subject descriptions (in English),Accept,Assessment Decision - No Decision,Assessment Decision - Qualified,OC - Created - English language requirements,OC - Reviewed - English language requirements,OC - Satisfied - English language requirements,OC - Satisfied - Evidence of course completion,Put Assessment On-Hold,Release Offer
CASE_ID,,,,,,,,,,,,,,,,,
766492|543478|831915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
582122|518867|795643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
832148|505702|776061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
831220|378450|589682,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1159316|546833|837110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [173]:
y_col_name = y.columns.values.tolist()
print(y_col_name)

['AR - Satisfied - Advanced Standing', 'AR - Satisfied - Credit for previous study', 'AR - Satisfied - Current enrolment at the University of Melbourne', 'AR - Satisfied - English language proficiency', 'AR - Satisfied - Further information (1)', 'AR - Satisfied - Further information Ã» Preference order required as submitted multiple 1st prefer applications', 'AR - Satisfied - Graduate Access Melbourne', 'AR - Satisfied - Official syllabus or subject descriptions (in English)', 'Accept', 'Assessment Decision - No Decision', 'Assessment Decision - Qualified', 'OC - Created - English language requirements', 'OC - Reviewed - English language requirements', 'OC - Satisfied - English language requirements', 'OC - Satisfied - Evidence of course completion', 'Put Assessment On-Hold', 'Release Offer']

In [174]:
for key in case_wf_dict.keys():
    for process in case_wf_dict[key]:
        if process in y_col_name:
            y.loc[key, process] = 1
        else:
            continue

In [175]:
pd.set_option('display.max_rows', None)

In [176]:
def movecol(df, cols_to_move=[], ref_col='', place='After'):
    
    cols = df.columns.tolist()
    if place == 'After':
        seg1 = cols[:list(cols).index(ref_col) + 1]
        seg2 = cols_to_move
    if place == 'Before':
        seg1 = cols[:list(cols).index(ref_col)]
        seg2 = cols_to_move + [ref_col]
    
    seg1 = [i for i in seg1 if i not in seg2]
    seg3 = [i for i in cols if i not in seg1 + seg2]
    
    return(df[seg1 + seg2 + seg3])

In [177]:
y.head()

,AR - Satisfied - Advanced Standing,AR - Satisfied - Credit for previous study,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - English language proficiency,AR - Satisfied - Further information (1),AR - Satisfied - Further information Ã» Preference order required as submitted multiple 1st prefer applications,AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Official syllabus or subject descriptions (in English),Accept,Assessment Decision - No Decision,Assessment Decision - Qualified,OC - Created - English language requirements,OC - Reviewed - English language requirements,OC - Satisfied - English language requirements,OC - Satisfied - Evidence of course completion,Put Assessment On-Hold,Release Offer
CASE_ID,,,,,,,,,,,,,,,,,
766492|543478|831915,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
582122|518867|795643,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
832148|505702|776061,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
831220|378450|589682,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1159316|546833|837110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0

In [179]:
y = movecol(y, 
             cols_to_move=['Release Offer'], 
             ref_col='AR - Satisfied - Advanced Standing',
             place='Before')

In [180]:
y = movecol(y, 
             cols_to_move=['Accept'], 
             ref_col='Put Assessment On-Hold',
             place='After')

In [181]:
y = movecol(y, 
             cols_to_move=['Defer'], 
             ref_col='Put Assessment On-Hold',
             place='After')

KeyError: "['Defer'] not in index"

In [182]:
pd.set_option('display.max_columns',None)

In [183]:
y.shape

(6, 17)

In [184]:
y=y.fillna(0.0)

In [185]:
X=y.iloc[:,0:16].values
Y=y.iloc[:,16].values

In [186]:
#spliting dataset
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size = 0.3,random_state=0)

In [187]:
# Linear SVM
svm = LinearSVC()
svm.fit(x_train, y_train)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 1.0

In [188]:
svm_predict = svm.predict(x_test)
print("accuracy: {}%".format(round(accuracy_score(y_test, svm_predict)*100,2)))

AttributeError: 'LinearSVC' object has no attribute 'coef_'

In [189]:
# Logistic Regression
lr = LogisticRegression()
lr.fit(x_train,y_train)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 1.0

In [190]:
lr_predict=lr.predict(x_test)
print("accuracy: {}%".format(round(accuracy_score(y_test, lr_predict)*100,2)))

AttributeError: 'LogisticRegression' object has no attribute 'coef_'

In [193]:
# K Nearest Neighbors
Knn = KNeighborsClassifier(n_neighbors=4)
Knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [194]:
knn_predict=Knn.predict(x_test)
print("accuracy: {}%".format(round(accuracy_score(y_test, knn_predict)*100,2)))

accuracy: 50.0%