In [1]:
import csv
import pandas as pd
from sklearn.linear_model import LogisticRegression 
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [2]:
segment3_workflow2=pd.read_csv('segment3_workflowS2.csv')
segment3_workflow2.CASE_ID.mode()

0    1114684|484215|743082
dtype: object

In [3]:
segment3_workflow3=pd.read_csv('segment3_workflowS3.csv')
segment3_workflow3.CASE_ID.mode()

0    1102908|470757|722758
dtype: object

In [4]:
segment3_workflow4=pd.read_csv('segment3_workflowS4.csv')
segment3_workflow4.CASE_ID.mode()

0    1052275|402830|625246
dtype: object

In [5]:
segment3_workflow2.head()

,CASE_ID,WRKFLW_TSK_MAP_GROUPED,WRKFLW_TSK_MAP_DETAILED,PATH_CRDATETIME,ITEM_CRUSER,WRKFLW_ORG_TYPE_CRUSER,STATUS_ORDER,LATEST_STATUS,WRKFLW_PROCESS,QUERY_PART,...,ORIG_SPRD_CD,ORIG_SPRD_NM,SPK_CAT_TYPE_CD,BROAD_COURSE_LEVEL,DEGREETYPE,LIABILITY_CATEGORY_CD_RECODE,ORIG_LIABILITY_CATEGORY_CD_RECODE,OFFER_RELEASED_FG,OFFER_OUTCOME_CD,OFFER_CONDITIONS
0,1067449|424909|657898,Send for Assessment,Send for Assessment,7/12/2018 11:01:50,1067449,NaN,9,N,1. App to Assessment,Part 1 - Application ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
1,1067449|424909|657898,Acacdemic - Assessment Decision - Qualified,Acacdemic - Assessment Decision - Qualified,14/12/2018 15:55:39,RGORDON1,Academic,8,N,2. Perform Assessment,Part 4 - Assessment Decision,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
2,1067449|424909|657898,Assessment Outcome - Successful,Assessment Outcome - Successful,18/12/2018 11:34:06,KRIT,Faculty,7,N,2. Perform Assessment,Part 3 - Assessment Outcome,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
3,913640|554685|848410,Send for Assessment,Send for Assessment,3/12/2019 11:06:46,913640,NaN,1,Y,1. App to Assessment,Part 1 - Application ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,NaN,NaN,NaN
4,1021374|367597|573577,Send for Assessment,Send for Assessment,26/6/2018 11:26:41,1021374,NaN,17,N,1. App to Assessment,Part 1 - Application ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N

In [6]:
segment3_workflow3.head()

,CASE_ID,WRKFLW_TSK_MAP_GROUPED,WRKFLW_TSK_MAP_DETAILED,PATH_CRDATETIME,ITEM_CRUSER,WRKFLW_ORG_TYPE_CRUSER,STATUS_ORDER,LATEST_STATUS,WRKFLW_PROCESS,QUERY_PART,...,ORIG_SPRD_CD,ORIG_SPRD_NM,SPK_CAT_TYPE_CD,BROAD_COURSE_LEVEL,DEGREETYPE,LIABILITY_CATEGORY_CD_RECODE,ORIG_LIABILITY_CATEGORY_CD_RECODE,OFFER_RELEASED_FG,OFFER_OUTCOME_CD,OFFER_CONDITIONS
0,1067449|424909|657898,Assessment Outcome - Successful,Assessment Outcome - Successful,18/12/2018 11:34:06,KRIT,Faculty,7,N,2. Perform Assessment,Part 3 - Assessment Outcome,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
1,1067449|424909|657898,Create Offer,Create Offer,18/12/2018 11:34:51,KRIT,Faculty,6,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
2,1067449|424909|657898,Release Offer,Release Offer,18/12/2018 11:36:07,KRIT,Faculty,5,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
3,1021374|367597|573577,Assessment Outcome - Successful,Assessment Outcome - Successful,12/7/2018 10:07:14,ATKINSONM,Faculty,12,N,2. Perform Assessment,Part 3 - Assessment Outcome,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N
4,1021374|367597|573577,Create Offer,Create Offer,12/7/2018 10:07:30,ATKINSONM,Faculty,11,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N

In [7]:
segment3_workflow3.head()

,CASE_ID,WRKFLW_TSK_MAP_GROUPED,WRKFLW_TSK_MAP_DETAILED,PATH_CRDATETIME,ITEM_CRUSER,WRKFLW_ORG_TYPE_CRUSER,STATUS_ORDER,LATEST_STATUS,WRKFLW_PROCESS,QUERY_PART,...,ORIG_SPRD_CD,ORIG_SPRD_NM,SPK_CAT_TYPE_CD,BROAD_COURSE_LEVEL,DEGREETYPE,LIABILITY_CATEGORY_CD_RECODE,ORIG_LIABILITY_CATEGORY_CD_RECODE,OFFER_RELEASED_FG,OFFER_OUTCOME_CD,OFFER_CONDITIONS
0,1067449|424909|657898,Assessment Outcome - Successful,Assessment Outcome - Successful,18/12/2018 11:34:06,KRIT,Faculty,7,N,2. Perform Assessment,Part 3 - Assessment Outcome,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
1,1067449|424909|657898,Create Offer,Create Offer,18/12/2018 11:34:51,KRIT,Faculty,6,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
2,1067449|424909|657898,Release Offer,Release Offer,18/12/2018 11:36:07,KRIT,Faculty,5,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,Y
3,1021374|367597|573577,Assessment Outcome - Successful,Assessment Outcome - Successful,12/7/2018 10:07:14,ATKINSONM,Faculty,12,N,2. Perform Assessment,Part 3 - Assessment Outcome,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N
4,1021374|367597|573577,Create Offer,Create Offer,12/7/2018 10:07:30,ATKINSONM,Faculty,11,N,3b. Offer stage,Part 2 - Application Line ID Workflow,...,STYI,Start Year Intake,MCW,HDCW,Full Degree,AF,AF,Y,$ACC,N

In [8]:
segment3_workflow2=segment3_workflow2.drop(['WRKFLW_TSK_MAP_GROUPED', 'PATH_CRDATETIME','ITEM_CRUSER','WRKFLW_ORG_TYPE_CRUSER',
                         'STATUS_ORDER','LATEST_STATUS','WRKFLW_PROCESS','QUERY_PART','REFERRAL_ID',
                         'APPLICATION_ID','STU_ID','STU_CITIZEN_CD','STU_CITIZEN_NM','STU_BIRTH_DT',
                         'STU_ABOR_TSI_CD','STU_ABOR_TSI_NM','STU_BIRTH_CNTRY_CD','STU_BIRTH_CNTRY_NM',
                         'STU_CTZN_CNTRY_CD','STU_CTZN_CNTRY_NM','SUBMISSION_METHOD','ENTRY_TYPE',
                         'ASSESSMENT_DECISION_SCORE','ASSESSMENT_DECISION_NM','ASSESSMENT_OUTCOME_NM',
                         'LAST_COUNTRY_EDUCATION','PREV_INST_NM_MAIN','PREV_INST_NM_ALT1','PREV_INST_NM_ALT2',
                        'PREFERENCE_NO','SPK_CD','SPK_FULL_TITLE','ORG_UNIT_CD','AVAIL_ORG_UNIT_NM','SUPPORTING_ORG',
                        'STUDY_MODE_CD','RETURNING_DEFERRAL','CURR_AVAIL_YR','CURR_STUDY_PERIOD','CURR_SPRD_CD',
                        'CURR_SPRD_NM','ORIG_AVAIL_YR','ORIG_STUDY_PERIOD','ORIG_SPRD_CD','ORIG_SPRD_NM',
                         'SPK_CAT_TYPE_CD','BROAD_COURSE_LEVEL','DEGREETYPE','LIABILITY_CATEGORY_CD_RECODE',
                        'ORIG_LIABILITY_CATEGORY_CD_RECODE','OFFER_RELEASED_FG','OFFER_OUTCOME_CD','OFFER_CONDITIONS',
                        'APPLICATION_LINE_ID'], axis=1)
segment3_workflow2.head()

                 CASE_ID                      WRKFLW_TSK_MAP_DETAILED
0  1067449|424909|657898                          Send for Assessment
1  1067449|424909|657898  Acacdemic - Assessment Decision - Qualified
2  1067449|424909|657898              Assessment Outcome - Successful
3   913640|554685|848410                          Send for Assessment
4  1021374|367597|573577                          Send for Assessment

In [9]:
segment3_workflow3=segment3_workflow3.drop(['WRKFLW_TSK_MAP_GROUPED', 'PATH_CRDATETIME','ITEM_CRUSER','WRKFLW_ORG_TYPE_CRUSER',
                         'STATUS_ORDER','LATEST_STATUS','WRKFLW_PROCESS','QUERY_PART','REFERRAL_ID',
                         'APPLICATION_ID','STU_ID','STU_CITIZEN_CD','STU_CITIZEN_NM','STU_BIRTH_DT',
                         'STU_ABOR_TSI_CD','STU_ABOR_TSI_NM','STU_BIRTH_CNTRY_CD','STU_BIRTH_CNTRY_NM',
                         'STU_CTZN_CNTRY_CD','STU_CTZN_CNTRY_NM','SUBMISSION_METHOD','ENTRY_TYPE',
                         'ASSESSMENT_DECISION_SCORE','ASSESSMENT_DECISION_NM','ASSESSMENT_OUTCOME_NM',
                         'LAST_COUNTRY_EDUCATION','PREV_INST_NM_MAIN','PREV_INST_NM_ALT1','PREV_INST_NM_ALT2',
                        'PREFERENCE_NO','SPK_CD','SPK_FULL_TITLE','ORG_UNIT_CD','AVAIL_ORG_UNIT_NM','SUPPORTING_ORG',
                        'STUDY_MODE_CD','RETURNING_DEFERRAL','CURR_AVAIL_YR','CURR_STUDY_PERIOD','CURR_SPRD_CD',
                        'CURR_SPRD_NM','ORIG_AVAIL_YR','ORIG_STUDY_PERIOD','ORIG_SPRD_CD','ORIG_SPRD_NM',
                         'SPK_CAT_TYPE_CD','BROAD_COURSE_LEVEL','DEGREETYPE','LIABILITY_CATEGORY_CD_RECODE',
                        'ORIG_LIABILITY_CATEGORY_CD_RECODE','OFFER_RELEASED_FG','OFFER_OUTCOME_CD','OFFER_CONDITIONS',
                        'APPLICATION_LINE_ID'], axis=1)
segment3_workflow3.head()

                 CASE_ID          WRKFLW_TSK_MAP_DETAILED
0  1067449|424909|657898  Assessment Outcome - Successful
1  1067449|424909|657898                     Create Offer
2  1067449|424909|657898                    Release Offer
3  1021374|367597|573577  Assessment Outcome - Successful
4  1021374|367597|573577                     Create Offer

In [11]:
segment3_workflow4=segment3_workflow4.drop(['WRKFLW_TSK_MAP_GROUPED', 'PATH_CRDATETIME','ITEM_CRUSER','WRKFLW_ORG_TYPE_CRUSER',
                         'STATUS_ORDER','LATEST_STATUS','WRKFLW_PROCESS','QUERY_PART','REFERRAL_ID',
                         'APPLICATION_ID','STU_ID','STU_CITIZEN_CD','STU_CITIZEN_NM','STU_BIRTH_DT',
                         'STU_ABOR_TSI_CD','STU_ABOR_TSI_NM','STU_BIRTH_CNTRY_CD','STU_BIRTH_CNTRY_NM',
                         'STU_CTZN_CNTRY_CD','STU_CTZN_CNTRY_NM','SUBMISSION_METHOD','ENTRY_TYPE',
                         'ASSESSMENT_DECISION_SCORE','ASSESSMENT_DECISION_NM','ASSESSMENT_OUTCOME_NM',
                         'LAST_COUNTRY_EDUCATION','PREV_INST_NM_MAIN','PREV_INST_NM_ALT1','PREV_INST_NM_ALT2',
                        'PREFERENCE_NO','SPK_CD','SPK_FULL_TITLE','ORG_UNIT_CD','AVAIL_ORG_UNIT_NM','SUPPORTING_ORG',
                        'STUDY_MODE_CD','RETURNING_DEFERRAL','CURR_AVAIL_YR','CURR_STUDY_PERIOD','CURR_SPRD_CD',
                        'CURR_SPRD_NM','ORIG_AVAIL_YR','ORIG_STUDY_PERIOD','ORIG_SPRD_CD','ORIG_SPRD_NM',
                         'SPK_CAT_TYPE_CD','BROAD_COURSE_LEVEL','DEGREETYPE','LIABILITY_CATEGORY_CD_RECODE',
                        'ORIG_LIABILITY_CATEGORY_CD_RECODE','OFFER_RELEASED_FG','OFFER_OUTCOME_CD','OFFER_CONDITIONS',
                        'APPLICATION_LINE_ID'], axis=1)
segment3_workflow4.head()

                 CASE_ID                         WRKFLW_TSK_MAP_DETAILED
0  1067449|424909|657898                                   Release Offer
1  1067449|424909|657898  OC - Satisfied - English language requirements
2  1067449|424909|657898                                          Accept
3  1021374|367597|573577                                   Release Offer
4  1021374|367597|573577                                          Accept

In [12]:
numOfWorkflowProcesses=segment3_workflow2.groupby('CASE_ID').CASE_ID.count()
numOfWorkflowProcesses.head()

CASE_ID
1000727|431447|668147    11
1001829|336678|526826     3
1001829|336678|526827     3
1001877|336757|526956    11
1002271|337186|527523     8
Name: CASE_ID, dtype: int64

In [13]:
numOfWorkflowProcesses2=segment3_workflow3.groupby('CASE_ID').CASE_ID.count()
numOfWorkflowProcesses2.head()

CASE_ID
1000727|431447|668147    4
1001829|336678|526826    3
1001877|336757|526956    3
1002271|337186|527523    3
1007394|346044|540306    3
Name: CASE_ID, dtype: int64

In [14]:
numOfWorkflowProcesses3=segment3_workflow3.groupby('CASE_ID').CASE_ID.count()
numOfWorkflowProcesses3.head()

CASE_ID
1000727|431447|668147    4
1001829|336678|526826    3
1001877|336757|526956    3
1002271|337186|527523    3
1007394|346044|540306    3
Name: CASE_ID, dtype: int64

In [15]:
counts = segment3_workflow2['CASE_ID'].value_counts()

In [16]:
counts2 = segment3_workflow3['CASE_ID'].value_counts()

In [17]:
counts3 = segment3_workflow3['CASE_ID'].value_counts()

In [18]:
counts.head()

1114684|484215|743082    22
1028582|370276|577743    16
1025815|366554|572153    15
1076583|437721|676610    15
1019820|360156|561476    15
Name: CASE_ID, dtype: int64

In [19]:
counts2.head()

1102908|470757|722758    12
1147799|528824|809849    11
1025815|366554|572153    10
1140264|517887|794176     9
1120436|490900|754192     9
Name: CASE_ID, dtype: int64

In [20]:
counts3.head()

1102908|470757|722758    12
1147799|528824|809849    11
1025815|366554|572153    10
1140264|517887|794176     9
1120436|490900|754192     9
Name: CASE_ID, dtype: int64

In [752]:
filtered = counts[counts == 5]
seg3_count1=segment3_workflow2[segment3_workflow2['CASE_ID'].isin(filtered.index)]

In [753]:
filtered2 = counts2[counts2 == 5]
seg3_count2=segment3_workflow3[segment3_workflow3['CASE_ID'].isin(filtered.index)]

In [754]:
filtered3 = counts3[counts3 == 5]
seg3_count3=segment3_workflow4[segment3_workflow4['CASE_ID'].isin(filtered.index)]

In [755]:
seg3_count1['CASE_ID'].nunique()

67

In [756]:
seg3_count1.head()

                  CASE_ID                            WRKFLW_TSK_MAP_DETAILED
44  1039537|384322|598550                                Send for Assessment
45  1039537|384322|598550                                     Back to Triage
46  1039537|384322|598550  AR - Satisfied - Entry points (Master of Infor...
47  1039537|384322|598550  AR - Satisfied - Specialisation (Master of Inf...
48  1039537|384322|598550                Assessment Outcome - Not Successful

In [757]:
seg3_count2['CASE_ID'].nunique()

50

In [758]:
seg3_count2.head()

                  CASE_ID              WRKFLW_TSK_MAP_DETAILED
21  1039537|384322|598550  Assessment Outcome - Not Successful
22  1039537|384322|598550    Assessment Decision - No Decision
23  1039537|384322|598550                  Send for Assessment
44  1048920|406016|629731      Assessment Outcome - Successful
45  1048920|406016|629731                         Create Offer

In [759]:
seg3_count3['CASE_ID'].nunique()

34

In [760]:
seg3_count3.head()

                  CASE_ID                        WRKFLW_TSK_MAP_DETAILED
22  1048920|406016|629731                                  Release Offer
23  1048920|406016|629731  OC - Reviewed - English language requirements
30  1111137|480052|736308                                  Release Offer
32  1111795|503247|772407                                  Release Offer
33  1111795|503247|772407                                         Accept

In [761]:
frames = [seg3_count1, seg3_count2, seg3_count3]
count_12=pd.concat(frames)

In [762]:
y = pd.get_dummies(seg3_count1.WRKFLW_TSK_MAP_DETAILED)
y=y[:0]

In [763]:
y

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1), AR - Created - Further information (1), AR - Created - Specialisation (Master of Engineering), AR - Not Satisfied - English language proficiency, AR - Reviewed - Graduate Access Melbourne, AR - Satisfied - Academic results for prior tertiary studies, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - English language proficiency, AR - Satisfied - Entry points (Master of Information Systems), AR - Satisfied - Entry points (Master of Information Technology), AR - Satisfied - Further information (1), AR - Satisfied - Graduate Access Melbourne, AR - Satisfied - Official syllabus or subject descriptions (in English), AR - Satisfied - Specialisation (Master of Information Systems), AR - Satisfied - Specialisation (Master of Information Technology), Acacdemic - Assessment Decision - No Decision, Acacdemic - Assessment Decision - Not Qualified, Acacdemic - Assessment Decision - Qualified, Assessment Decision - No Decision, Assessment Decision - Not Qualified, Assessment Decision - Qualified, Assessment Decision - System Assessed, Assessment Outcome - Higher Preference Successful, Assessment Outcome - Ineligible / Withdrawn, Assessment Outcome - Not Successful, Assessment Outcome - Successful, Back to Triage, Close Referral, End My Assessment, OC - Created - Evidence of course completion, OC - Reviewed - English language requirements, OC - Satisfied - Evidence of course completion, Provide Response, Put Assessment On-Hold, Release Assessment Hold, Send Referral, Send for Assessment]
Index: []

In [764]:
y2 = pd.get_dummies(seg3_count2.WRKFLW_TSK_MAP_DETAILED)
y2=y2[:0]

In [765]:
y2

Empty DataFrame
Columns: [AR - Satisfied - Curriculum Vitae and professional experience, Assessment Decision - No Decision, Assessment Decision - Qualified, Assessment Outcome - Not Successful, Assessment Outcome - Successful, Create Offer, End My Assessment, OC - Created - English language requirements, OC - Created - Evidence of course completion, OC - Reviewed - English language requirements, Release Offer, Send for Assessment]
Index: []

In [766]:
y3 = pd.get_dummies(seg3_count3.WRKFLW_TSK_MAP_DETAILED)
y3=y3[:0]

In [767]:
y3

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1), AR - Satisfied - Academic results for prior tertiary studies, AR - Satisfied - English language proficiency, Accept, Back to Perform Assessment, Defer, Manage Acceptance, OC - Created - Evidence of course completion, OC - Reviewed - English language requirements, OC - Satisfied - English language requirements, OC - Satisfied - Evidence of course completion, PREPARE TO LOCK, Put Assessment On-Hold, Release Assessment Hold, Release Offer]
Index: []

In [768]:
y4=pd.merge(y, y2, on='Assessment Outcome - Successful')
y4

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1), AR - Created - Further information (1), AR - Created - Specialisation (Master of Engineering), AR - Not Satisfied - English language proficiency, AR - Reviewed - Graduate Access Melbourne, AR - Satisfied - Academic results for prior tertiary studies, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - English language proficiency, AR - Satisfied - Entry points (Master of Information Systems), AR - Satisfied - Entry points (Master of Information Technology), AR - Satisfied - Further information (1), AR - Satisfied - Graduate Access Melbourne, AR - Satisfied - Official syllabus or subject descriptions (in English), AR - Satisfied - Specialisation (Master of Information Systems), AR - Satisfied - Specialisation (Master of Information Technology), Acacdemic - Assessment Decision - No Decision, Acacdemic - Assessment Decision - Not Qualified, Acacdemic - Assessment Decision - Qualified, Assessment Decision - No Decision_x, Assessment Decision - Not Qualified, Assessment Decision - Qualified_x, Assessment Decision - System Assessed, Assessment Outcome - Higher Preference Successful, Assessment Outcome - Ineligible / Withdrawn, Assessment Outcome - Not Successful_x, Back to Triage, Close Referral, End My Assessment_x, OC - Created - Evidence of course completion_x, OC - Reviewed - English language requirements_x, OC - Satisfied - Evidence of course completion, Provide Response, Put Assessment On-Hold, Release Assessment Hold, Send Referral, Send for Assessment_x, AR - Satisfied - Curriculum Vitae and professional experience, Assessment Decision - No Decision_y, Assessment Decision - Qualified_y, Assessment Outcome - Not Successful_y, Assessment Outcome - Successful, Create Offer, End My Assessment_y, OC - Created - English language requirements, OC - Created - Evidence of course completion_y, OC - Reviewed - English language requirements_y, Release Offer, Send for Assessment_y]
Index: []

In [769]:
y4.columns = y4.columns.str.replace("_x", "")

In [770]:
y4.columns = y4.columns.str.replace("_y", "")

In [771]:
y4 = y4.loc[:,~y4.columns.duplicated()]

In [772]:
y4.shape

(0, 41)

In [773]:
y5=pd.merge(y3, y4, on='Release Offer')
y5

Empty DataFrame
Columns: [AR - Created - Assessment information (Coursework) (1)_x, AR - Satisfied - Academic results for prior tertiary studies_x, AR - Satisfied - English language proficiency_x, Accept, Back to Perform Assessment, Defer, Manage Acceptance, OC - Created - Evidence of course completion_x, OC - Reviewed - English language requirements_x, OC - Satisfied - English language requirements, OC - Satisfied - Evidence of course completion_x, PREPARE TO LOCK, Put Assessment On-Hold_x, Release Assessment Hold_x, AR - Created - Assessment information (Coursework) (1)_y, AR - Created - Further information (1), AR - Created - Specialisation (Master of Engineering), AR - Not Satisfied - English language proficiency, AR - Reviewed - Graduate Access Melbourne, AR - Satisfied - Academic results for prior tertiary studies_y, AR - Satisfied - Current enrolment at the University of Melbourne, AR - Satisfied - English language proficiency_y, AR - Satisfied - Entry points (Master of Information Systems), AR - Satisfied - Entry points (Master of Information Technology), AR - Satisfied - Further information (1), AR - Satisfied - Graduate Access Melbourne, AR - Satisfied - Official syllabus or subject descriptions (in English), AR - Satisfied - Specialisation (Master of Information Systems), AR - Satisfied - Specialisation (Master of Information Technology), Acacdemic - Assessment Decision - No Decision, Acacdemic - Assessment Decision - Not Qualified, Acacdemic - Assessment Decision - Qualified, Assessment Decision - No Decision, Assessment Decision - Not Qualified, Assessment Decision - Qualified, Assessment Decision - System Assessed, Assessment Outcome - Higher Preference Successful, Assessment Outcome - Ineligible / Withdrawn, Assessment Outcome - Not Successful, Back to Triage, Close Referral, End My Assessment, OC - Created - Evidence of course completion_y, OC - Reviewed - English language requirements_y, OC - Satisfied - Evidence of course completion_y, Provide Response, Put Assessment On-Hold_y, Release Assessment Hold_y, Send Referral, Send for Assessment, AR - Satisfied - Curriculum Vitae and professional experience, Assessment Outcome - Successful, Create Offer, OC - Created - English language requirements, Release Offer]
Index: []

In [774]:
y5.columns = y5.columns.str.replace("_x", "")

In [775]:
y5.columns = y5.columns.str.replace("_y", "")

In [776]:
y5 = y5.loc[:,~y5.columns.duplicated()]

In [777]:
y5.shape

(0, 47)

In [778]:
y5["CASE_ID"]=""

In [779]:
col_name="CASE_ID"
first_col = y5.pop(col_name)

In [780]:
y5.insert(0, col_name, first_col)

In [781]:
y5['CASE_ID']=count_12['CASE_ID'].unique()

<ipython-input-781-da8cd2d0614a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y5['CASE_ID']=count_12['CASE_ID'].unique()

In [782]:
import numpy as np
y5 = y5.replace(np.nan,0, regex=True)
y5.head()

,CASE_ID,AR - Created - Assessment information (Coursework) (1),AR - Satisfied - Academic results for prior tertiary studies,AR - Satisfied - English language proficiency,Accept,Back to Perform Assessment,Defer,Manage Acceptance,OC - Created - Evidence of course completion,OC - Reviewed - English language requirements,OC - Satisfied - English language requirements,OC - Satisfied - Evidence of course completion,PREPARE TO LOCK,Put Assessment On-Hold,Release Assessment Hold,AR - Created - Further information (1),AR - Created - Specialisation (Master of Engineering),AR - Not Satisfied - English language proficiency,AR - Reviewed - Graduate Access Melbourne,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - Entry points (Master of Information Systems),AR - Satisfied - Entry points (Master of Information Technology),AR - Satisfied - Further information (1),AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Official syllabus or subject descriptions (in English),AR - Satisfied - Specialisation (Master of Information Systems),AR - Satisfied - Specialisation (Master of Information Technology),Acacdemic - Assessment Decision - No Decision,Acacdemic - Assessment Decision - Not Qualified,Acacdemic - Assessment Decision - Qualified,Assessment Decision - No Decision,Assessment Decision - Not Qualified,Assessment Decision - Qualified,Assessment Decision - System Assessed,Assessment Outcome - Higher Preference Successful,Assessment Outcome - Ineligible / Withdrawn,Assessment Outcome - Not Successful,Back to Triage,Close Referral,End My Assessment,Provide Response,Send Referral,Send for Assessment,AR - Satisfied - Curriculum Vitae and professional experience,Assessment Outcome - Successful,Create Offer,OC - Created - English language requirements,Release Offer
0,1039537|384322|598550,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1048920|406016|629731,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1111137|480052|736308,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1111795|503247|772407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1132420|507235|778296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [783]:
dict_1=count_12.to_dict(orient='list')

In [784]:
case_id = dict_1['CASE_ID']

In [785]:
workflow = dict_1['WRKFLW_TSK_MAP_DETAILED']

In [786]:
print(type(workflow))
print(len(workflow))

<class 'list'>
542

In [787]:
from collections import defaultdict

case_wf_dict = defaultdict(list)

for i in range(len(case_id)):
    item = case_id[i]
    case_wf_dict[item].append(workflow[i])
print(len(case_wf_dict))

67

In [788]:
y5 = y5.set_index('CASE_ID')

In [789]:
y5.head()

,AR - Created - Assessment information (Coursework) (1),AR - Satisfied - Academic results for prior tertiary studies,AR - Satisfied - English language proficiency,Accept,Back to Perform Assessment,Defer,Manage Acceptance,OC - Created - Evidence of course completion,OC - Reviewed - English language requirements,OC - Satisfied - English language requirements,OC - Satisfied - Evidence of course completion,PREPARE TO LOCK,Put Assessment On-Hold,Release Assessment Hold,AR - Created - Further information (1),AR - Created - Specialisation (Master of Engineering),AR - Not Satisfied - English language proficiency,AR - Reviewed - Graduate Access Melbourne,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - Entry points (Master of Information Systems),AR - Satisfied - Entry points (Master of Information Technology),AR - Satisfied - Further information (1),AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Official syllabus or subject descriptions (in English),AR - Satisfied - Specialisation (Master of Information Systems),AR - Satisfied - Specialisation (Master of Information Technology),Acacdemic - Assessment Decision - No Decision,Acacdemic - Assessment Decision - Not Qualified,Acacdemic - Assessment Decision - Qualified,Assessment Decision - No Decision,Assessment Decision - Not Qualified,Assessment Decision - Qualified,Assessment Decision - System Assessed,Assessment Outcome - Higher Preference Successful,Assessment Outcome - Ineligible / Withdrawn,Assessment Outcome - Not Successful,Back to Triage,Close Referral,End My Assessment,Provide Response,Send Referral,Send for Assessment,AR - Satisfied - Curriculum Vitae and professional experience,Assessment Outcome - Successful,Create Offer,OC - Created - English language requirements,Release Offer
CASE_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1039537|384322|598550,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1048920|406016|629731,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1111137|480052|736308,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1111795|503247|772407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1132420|507235|778296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [790]:
y_col_name = y5.columns.values.tolist()
print(y_col_name)

['AR - Created - Assessment information (Coursework) (1)', 'AR - Satisfied - Academic results for prior tertiary studies', 'AR - Satisfied - English language proficiency', 'Accept', 'Back to Perform Assessment', 'Defer', 'Manage Acceptance', 'OC - Created - Evidence of course completion', 'OC - Reviewed - English language requirements', 'OC - Satisfied - English language requirements', 'OC - Satisfied - Evidence of course completion', 'PREPARE TO LOCK', 'Put Assessment On-Hold', 'Release Assessment Hold', 'AR - Created - Further information (1)', 'AR - Created - Specialisation (Master of Engineering)', 'AR - Not Satisfied - English language proficiency', 'AR - Reviewed - Graduate Access Melbourne', 'AR - Satisfied - Current enrolment at the University of Melbourne', 'AR - Satisfied - Entry points (Master of Information Systems)', 'AR - Satisfied - Entry points (Master of Information Technology)', 'AR - Satisfied - Further information (1)', 'AR - Satisfied - Graduate Access Melbourne', 'AR - Satisfied - Official syllabus or subject descriptions (in English)', 'AR - Satisfied - Specialisation (Master of Information Systems)', 'AR - Satisfied - Specialisation (Master of Information Technology)', 'Acacdemic - Assessment Decision - No Decision', 'Acacdemic - Assessment Decision - Not Qualified', 'Acacdemic - Assessment Decision - Qualified', 'Assessment Decision - No Decision', 'Assessment Decision - Not Qualified', 'Assessment Decision - Qualified', 'Assessment Decision - System Assessed', 'Assessment Outcome - Higher Preference Successful', 'Assessment Outcome - Ineligible / Withdrawn', 'Assessment Outcome - Not Successful', 'Back to Triage', 'Close Referral', 'End My Assessment', 'Provide Response', 'Send Referral', 'Send for Assessment', 'AR - Satisfied - Curriculum Vitae and professional experience', 'Assessment Outcome - Successful', 'Create Offer', 'OC - Created - English language requirements', 'Release Offer']

In [791]:
for key in case_wf_dict.keys():
    for process in case_wf_dict[key]:
        if process in y_col_name:
            y5.loc[key, process] = 1
        else:
            continue

In [792]:
pd.set_option('display.max_columns', None)

In [793]:
y5['Send for Assessment'].head()

CASE_ID
1039537|384322|598550    1.0
1048920|406016|629731    1.0
1111137|480052|736308    1.0
1111795|503247|772407    1.0
1132420|507235|778296    1.0
Name: Send for Assessment, dtype: float64

In [794]:
def movecol(df, cols_to_move=[], ref_col='', place='After'):
    
    cols = df.columns.tolist()
    if place == 'After':
        seg1 = cols[:list(cols).index(ref_col) + 1]
        seg2 = cols_to_move
    if place == 'Before':
        seg1 = cols[:list(cols).index(ref_col)]
        seg2 = cols_to_move + [ref_col]
    
    seg1 = [i for i in seg1 if i not in seg2]
    seg3 = [i for i in cols if i not in seg1 + seg2]
    
    return(df[seg1 + seg2 + seg3])

In [795]:
y5.head()

,AR - Created - Assessment information (Coursework) (1),AR - Satisfied - Academic results for prior tertiary studies,AR - Satisfied - English language proficiency,Accept,Back to Perform Assessment,Defer,Manage Acceptance,OC - Created - Evidence of course completion,OC - Reviewed - English language requirements,OC - Satisfied - English language requirements,OC - Satisfied - Evidence of course completion,PREPARE TO LOCK,Put Assessment On-Hold,Release Assessment Hold,AR - Created - Further information (1),AR - Created - Specialisation (Master of Engineering),AR - Not Satisfied - English language proficiency,AR - Reviewed - Graduate Access Melbourne,AR - Satisfied - Current enrolment at the University of Melbourne,AR - Satisfied - Entry points (Master of Information Systems),AR - Satisfied - Entry points (Master of Information Technology),AR - Satisfied - Further information (1),AR - Satisfied - Graduate Access Melbourne,AR - Satisfied - Official syllabus or subject descriptions (in English),AR - Satisfied - Specialisation (Master of Information Systems),AR - Satisfied - Specialisation (Master of Information Technology),Acacdemic - Assessment Decision - No Decision,Acacdemic - Assessment Decision - Not Qualified,Acacdemic - Assessment Decision - Qualified,Assessment Decision - No Decision,Assessment Decision - Not Qualified,Assessment Decision - Qualified,Assessment Decision - System Assessed,Assessment Outcome - Higher Preference Successful,Assessment Outcome - Ineligible / Withdrawn,Assessment Outcome - Not Successful,Back to Triage,Close Referral,End My Assessment,Provide Response,Send Referral,Send for Assessment,AR - Satisfied - Curriculum Vitae and professional experience,Assessment Outcome - Successful,Create Offer,OC - Created - English language requirements,Release Offer
CASE_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1039537|384322|598550,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1048920|406016|629731,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
1111137|480052|736308,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
1111795|503247|772407,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
1132420|507235|778296,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0

In [796]:
y5 = movecol(y5, 
             cols_to_move=['Accept'], 
             ref_col='Release Offer',
             place='After')

In [797]:
y5 = movecol(y5, 
             cols_to_move=['Defer'], 
             ref_col='Release Offer',
             place='After')

In [798]:
y5.shape

(67, 47)

In [799]:
y5=y5.fillna(0.0)

In [800]:
X=y5.iloc[:,0:45].values
Y=y5.iloc[:,45:47].values

In [801]:
#spliting dataset
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size = 0.3,random_state=0)

In [803]:
# K Nearest Neighbors
Knn = KNeighborsClassifier(n_neighbors=5)
Knn.fit(x_train,y_train)

KNeighborsClassifier()

In [804]:
knn_predict=Knn.predict(x_test)
print("accuracy: {}%".format(round(accuracy_score(y_test, knn_predict)*100,2)))

accuracy: 85.71%